
climate:  
  - platform: thermostat
    id: ${name}_thermostat
    name: ${name}
    sensor: ${ch1_thermostat_sensor}
    default_preset: default
    on_boot_restore_from: memory
    startup_delay: true
    preset:
      - name: default
        default_target_temperature_low: ${ch1_default_target_temperature_low}
        default_target_temperature_high: ${ch1_default_target_temperature_high}
        mode: HEAT_COOL
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action: 
         - lambda: 'return;' # do nothing cause action is triggered by time interval
    cool_action:
         - lambda: 'return;' 
    idle_action:
         - lambda: 'return;' 
    visual:
      min_temperature: 10 °C
      max_temperature: 30 °C
      temperature_step: 0.1 °C
      
