
number:
    ## #for 0 V and 0.1 V you’ll get the same value: 0 https://randomnerdtutorials.com/esp32-adc-analog-read-arduino-ide/    
    
  - platform: template
    name: "bemf_trigger_1"
    optimistic: true
    min_value: 0.05
    max_value: 150.00
    step: 0.05
    restore_value: true
    initial_value: ${ch1_bemf_trigger}
    id: ${name}_bemf_trigger_1

 

  # - platform: template
    # name: "rollback %"
    # optimistic: true
    # min_value: 1
    # max_value: 10
    # step: 1
    # restore_value: true
    # initial_value: ${endstop_rollback_percent}
    # id: ${name}_rollback    
    
  - platform: template
    name: "min movement change %"
    optimistic: true
    min_value: 1
    max_value: 25
    step: 1
    restore_value: true
    initial_value: 5
    id: ${name}_min_movement 