
wifi:
  networks:
  - ssid: !secret wifi_ssid_1
    hidden: true
    password: !secret wifi_password_1
    priority : 1
  - ssid: !secret wifi_ssid_2
    hidden: true
    password: !secret wifi_password_2
    priority : 2
  - ssid: !secret wifi_ssid_3
    password: !secret wifi_password_3
    priority : 3
#  use_address: floor_heating_controller.local

# Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
    # ssid: "${name} Flbck"
    # password: !secret fallback_hotspot_password
#captive_portal:

